services:
  bot:
    build: .
    restart: always
    depends_on:
      - redis
    environment:
      INSTAGRAM_USER: "${INSTAGRAM_USER}"
      INSTAGRAM_PASS: "${INSTAGRAM_PASS}"
      MONGO_URI: "${MONGO_URL}"
      REDIS_URL: "${REDIS_URL}"
