version: "3.8"

services:
  redis:
    image: redis:latest
    restart: always
    expose:
      - "6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 3
      timeout: 5s

  bot:
    build: .
    restart: always
    depends_on:
      redis:
        condition: service_healthy
    environment:
      INSTAGRAM_USER: "${INSTAGRAM_USER}"
      INSTAGRAM_PASS: "${INSTAGRAM_PASS}"
      MONGO_URI: "mongodb.railway.internal"
      REDIS_URL: "redis.railway.internal"  # <--- Cambiado para asegurar conexión local a Redis
    command: sh -c "celery -A bot_instagram worker --loglevel=info --concurrency=2 --pool=solo --without-heartbeat & while true; do sleep 30; done"
    user: "myuser"

