version: '3.8'

services:
  bot:
    build: .
    restart: always
    depends_on:
      - redis
    environment:
      INSTAGRAM_USER: "${INSTAGRAM_USER}"
      INSTAGRAM_PASS: "${INSTAGRAM_PASS}"
      MONGO_URI: "${MONGO_URI}"
      REDIS_URL: "redis://default:ltFAcydADlvycKkCMxqYypbeEEyQNZjN@redis.railway.internal:6379"

  redis:
    image: "redis:alpine"
    restart: always
